name: Update Final
on:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update all branches
      run: |
        git fetch --all
        git checkout main && git pull
        git checkout feature/vsetv-click && git pull
        git checkout feature/ontivi && git pull
